### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by celorodovalho**
No incompatibility with version 7.2 found

### CODE REVIEW

**Comment by jruzafa** [comment]
From my point of view, is not it more convenient to be 7.2. *? Normally the minor versions do not affect compatibility.

**Comment by celorodovalho** [comment]
The tilde (~) in composer dependencies means:
```
The ~ operator is best explained by example: ~1.2 is equivalent to >=1.2 <2.0.0, while ~1.2.3 is equivalent to >=1.2.3 <1.3.0.

Another way of looking at it is that using ~ specifies a minimum version, but allows the last digit specified to go up.
```
https://getcomposer.org/doc/articles/versions.md#tilde-version-range-

So, this way ~7.2.0 works properly as 7.2.*
And I just follow the previous pattern also.

**Comment by mbijnsdorp** [comment]
@avstudnitz

**Comment by avstudnitz** [comment]
Hmm, I'd prefer having the version constraint for PHP removed completely. That should be the framework's responsibility. I'll do that.

**Pull request closed without merging**
