### PR TITLE
Fixing Category Import

### PR DESCRIPTION
**Pull request by blewinsky**
- Removed _ (underscores) of vars/functions according http://www.php-fig.org/psr/psr-2/#4-2-properties
- Added ignoreDuplicates config
- Added possibility to upload file
- Corrected deletion of category
- And some little bugfixes

### CODE REVIEW

**Comment by EliasKotlyar** [comment]
Hello blewinsky,

Your PR was merged, and it has improved the module a lot. Many thanks!

PS: Could you please tell me, for which usecase you are using the proxy (FireGento\FastSimpleImport\Model\Import\Proxy\Category)? 

Greetings
Elias

**Comment by EliasKotlyar** [comment]
Hello blewinsky,

I have refactored the Code, and removed the dependency on the Enterprise Edition. 

Could you please test if the Code for Content Staging is still working? I dont have a Enterprise Edition here, so i cannot test it.

Many Thanks,

Greetings
Elias

**Comment by blewinsky** [comment]
Hi Elias,
Ill check it

**Comment by blewinsky** [comment]
btw, i see that this module dosnt use versions... is there a reason for that?

**Comment by EliasKotlyar** [comment]
Hello blewinsky,

Actually,  there is a reason. This plugin support both Versions of Magento2, Community and Enterprise. The Content-Staging is supported only by the M2 Enterprise Edition.

Greetings
Elias

**Comment by blewinsky** [comment]
got error
```
PHP Fatal error:  Uncaught Error: Call to a member function get() on null in /resources/fileshare/releases/20161006114833/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:126
```

**Comment by blewinsky** [comment]
you'll get PR today for Enterprise ;)

**Pull request merged**
